### ISSUE TITLE
Option to remove and add titles without enter into the information

### ISSUE THREAD

**Issue by mperez01** [WyrnCael/JotDownThatMovie#14]
Example of the idea:

Remove
<img src="https://user-images.githubusercontent.com/32309834/52282649-2ae92600-2961-11e9-9a3f-e9a5dd1bd1a7.png" width="400">

Add
<img src="https://user-images.githubusercontent.com/32309834/52282927-c37fa600-2961-11e9-9a46-2839d1f6a363.png" width="400">

**Comment by WyrnCael** [comment]
I like the idea, but with this we lose the actual record type information (Movie or TV Show) showed at the right side icon:

<img src="https://i.imgur.com/vmCbpef.png" width="400">

This enhancement requires doing a complete redesign of record types or maybe show the record type when swipe, but adds complexity to standard user:

<img src="https://raw.githubusercontent.com/baoyongzhang/SwipeMenuListView/master/demo3.gif" width="400">

I will make some test and take the most easy way for the final user.
